# Generated by Django 4.2.23 on 2025-08-25 01:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agency_name', models.CharField(max_length=255)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['agency_name'],
            },
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('ein', models.CharField(help_text='Format: XX-XXXXXXX', max_length=11, unique=True)),
                ('size', models.IntegerField(help_text='Number of employees (max 100 for small group)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('effective_date', models.DateField()),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('terminated', 'Terminated')], default='pending', max_length=15)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employers', to='broker_console.broker')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('plan_type', models.CharField(choices=[('medical', 'Medical'), ('dental', 'Dental'), ('vision', 'Vision'), ('life', 'Life/AD&D')], max_length=20)),
                ('external_code', models.CharField(help_text="Carrier's plan code", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='broker_console.carrier')),
            ],
            options={
                'ordering': ['carrier__name', 'plan_type', 'name'],
                'unique_together': {('carrier', 'external_code')},
            },
        ),
        migrations.CreateModel(
            name='PlanPremium',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coverage_tier', models.CharField(choices=[('employee_only', 'Employee Only'), ('employee_spouse', 'Employee + Spouse'), ('employee_children', 'Employee + Child(ren)'), ('family', 'Family')], max_length=20)),
                ('monthly_premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premiums', to='broker_console.plan')),
            ],
            options={
                'ordering': ['plan', 'coverage_tier', 'effective_date'],
            },
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coverage_type', models.CharField(choices=[('medical', 'Medical'), ('dental', 'Dental'), ('vision', 'Vision'), ('life', 'Life/AD&D')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker_console.carrier')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='broker_console.employer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarrierCsvTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('coverage_type', models.CharField(choices=[('medical', 'Medical'), ('dental', 'Dental'), ('vision', 'Vision'), ('life', 'Life/AD&D')], max_length=20)),
                ('template_fields', models.JSONField(help_text='Array of field definitions')),
                ('is_active', models.BooleanField(default=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_templates', to='broker_console.carrier')),
            ],
            options={
                'ordering': ['carrier', 'coverage_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmployerOffering',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('contribution_mode', models.CharField(choices=[('full', 'Full (100%)'), ('percent', 'Percentage'), ('fixed', 'Fixed Amount')], default='full', max_length=10)),
                ('contribution_value', models.DecimalField(decimal_places=2, default=0, help_text='Percentage (0-100) or fixed dollar amount', max_digits=10)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='broker_console.employer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker_console.plan')),
            ],
            options={
                'ordering': ['employer', 'plan'],
                'unique_together': {('employer', 'plan')},
            },
        ),
        migrations.CreateModel(
            name='BrokerUser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='broker_console.broker')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'broker')},
            },
        ),
    ]
