# Generated by Django 4.2.23 on 2025-08-25 11:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('broker_console', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(help_text="Employer's employee ID", max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=1)),
                ('ssn', models.CharField(help_text='Format: XXX-XX-XXXX', max_length=11)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='single', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('hire_date', models.DateField()),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, help_text='Annual salary', max_digits=10)),
                ('hours_per_week', models.DecimalField(decimal_places=1, default=40.0, max_digits=4)),
                ('employment_status', models.CharField(default='active', max_length=20)),
                ('medical_coverage_tier', models.CharField(blank=True, choices=[('employee_only', 'Employee Only'), ('employee_spouse', 'Employee + Spouse'), ('employee_children', 'Employee + Child(ren)'), ('family', 'Family')], max_length=20)),
                ('dental_coverage_tier', models.CharField(blank=True, choices=[('employee_only', 'Employee Only'), ('employee_spouse', 'Employee + Spouse'), ('employee_children', 'Employee + Child(ren)'), ('family', 'Family')], max_length=20)),
                ('vision_coverage_tier', models.CharField(blank=True, choices=[('employee_only', 'Employee Only'), ('employee_spouse', 'Employee + Spouse'), ('employee_children', 'Employee + Child(ren)'), ('family', 'Family')], max_length=20)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='broker_console.employer')),
            ],
            options={
                'ordering': ['employer', 'last_name', 'first_name'],
                'unique_together': {('employer', 'employee_id')},
            },
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=1)),
                ('ssn', models.CharField(blank=True, help_text='Format: XXX-XX-XXXX', max_length=11)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse'), ('child', 'Child'), ('domestic_partner', 'Domestic Partner')], max_length=20)),
                ('medical_coverage', models.BooleanField(default=False)),
                ('dental_coverage', models.BooleanField(default=False)),
                ('vision_coverage', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='broker_console.employee')),
            ],
            options={
                'ordering': ['employee', 'relationship', 'last_name'],
            },
        ),
    ]
