# Generated by Django 5.2.5 on 2025-08-28 04:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_console', '0002_employee_dependent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentPeriod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('period_type', models.CharField(choices=[('open_enrollment', 'Open Enrollment'), ('initial_enrollment', 'Initial Enrollment'), ('qualifying_event', 'Qualifying Life Event'), ('special_enrollment', 'Special Enrollment')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('coverage_effective_date', models.DateField()),
                ('allow_waive', models.BooleanField(default=True, help_text='Allow employees to waive coverage')),
                ('require_all_plans', models.BooleanField(default=False, help_text='Require election for all plan types')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_periods', to='broker_console.employer')),
            ],
            options={
                'ordering': ['-coverage_effective_date', 'employer'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeEnrollment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('declined', 'Declined'), ('expired', 'Expired')], default='not_started', max_length=15)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('waived_coverage', models.BooleanField(default=False)),
                ('waiver_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='broker_console.employee')),
                ('enrollment_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_enrollments', to='broker_console.enrollmentperiod')),
            ],
            options={
                'ordering': ['-enrollment_period__coverage_effective_date', 'employee'],
                'unique_together': {('employee', 'enrollment_period')},
            },
        ),
        migrations.CreateModel(
            name='PlanEnrollment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('waived', 'Waived'), ('declined', 'Declined'), ('terminated', 'Terminated')], default='enrolled', max_length=15)),
                ('coverage_tier', models.CharField(choices=[('employee_only', 'Employee Only'), ('employee_spouse', 'Employee + Spouse'), ('employee_children', 'Employee + Child(ren)'), ('family', 'Family')], max_length=20)),
                ('monthly_premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employer_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('effective_date', models.DateField()),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('covered_dependents', models.ManyToManyField(blank=True, help_text='Dependents covered under this enrollment', to='broker_console.dependent')),
                ('employee_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_enrollments', to='broker_console.employeeenrollment')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker_console.plan')),
            ],
            options={
                'ordering': ['employee_enrollment', 'plan'],
                'unique_together': {('employee_enrollment', 'plan')},
            },
        ),
        migrations.CreateModel(
            name='EnrollmentEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('enrollment', 'New Enrollment'), ('change', 'Plan Change'), ('termination', 'Coverage Termination'), ('reinstatement', 'Coverage Reinstatement'), ('dependent_add', 'Dependent Added'), ('dependent_remove', 'Dependent Removed'), ('waiver', 'Coverage Waived')], max_length=20)),
                ('effective_date', models.DateField()),
                ('previous_coverage_tier', models.CharField(blank=True, choices=[('employee_only', 'Employee Only'), ('employee_spouse', 'Employee + Spouse'), ('employee_children', 'Employee + Child(ren)'), ('family', 'Family')], max_length=20)),
                ('new_coverage_tier', models.CharField(blank=True, choices=[('employee_only', 'Employee Only'), ('employee_spouse', 'Employee + Spouse'), ('employee_children', 'Employee + Child(ren)'), ('family', 'Family')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_events', to='broker_console.employee')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plan_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='broker_console.planenrollment')),
            ],
            options={
                'ordering': ['-effective_date', '-processed_at'],
            },
        ),
    ]
